const CHATS_TYPES = {
	JOIN_CHAT: '@chats/JOIN_CHAT',
	FETCH_CHATS_STARTED: '@chats/FETCH_CHATS_STARTED',
	FETCH_CHATS_SUCCESS: '@chats/FETCH_CHATS_SUCCESS',
	FETCH_CHATS_ERROR: '@chats/FETCH_CHATS_ERROR',
	FETCH_JOINED_CHATS_STARTED: '@chats/FETCH_JOINED_CHATS_STARTED',
	FETCH_JOINED_CHATS_SUCCESS: '@chats/FETCH_JOINED_CHATS_SUCCESS',
	FETCH_JOINED_CHATS_FAILURE: '@chats/FETCH_JOINED_CHATS_FAILURE',
}

export default CHATS_TYPES;
