const AUTH_TYPES = {
	REGISTER_USER_EMAIL_AND_PASSWORD_STARTED: '@auth/REGISTER_USER_EMAIL_AND_PASSWORD_STARTED',
	REGISTER_USER_EMAIL_AND_PASSWORD_SUCCESS: '@auth/REGISTER_USER_EMAIL_AND_PASSWORD_SUCCESS',
	REGISTER_USER_EMAIL_AND_PASSWORD_FAILURE: '@auth/REGISTER_USER_EMAIL_AND_PASSWORD_FAILURE',
	SET_USER_DATA: '@auth/SET_USER_DATA',
}

export default AUTH_TYPES;
