const AUTH_TYPES = {
	REGISTER_USER_EMAIL_AND_PASSWORD_STARTED: '@auth/REGISTER_USER_EMAIL_AND_PASSWORD_STARTED',
	REGISTER_USER_EMAIL_AND_PASSWORD_SUCCESS: '@auth/REGISTER_USER_EMAIL_AND_PASSWORD_SUCCESS',
	REGISTER_USER_EMAIL_AND_PASSWORD_FAILURE: '@auth/REGISTER_USER_EMAIL_AND_PASSWORD_FAILURE',
	SET_USER_DATA: '@auth/SET_USER_DATA',
	SIGN_OUT_SUCCESS: '@auth/SIGN_OUT_SUCCESS',
	SIGN_OUT_FAILURE: '@auth/SIGN_OUT_FAILURE',
	SIGN_IN_FAILURE: '@auth/SIGN_IN_FAILURE',
}

export default AUTH_TYPES;
